### ISSUE TITLE
文档的配置项中缺少函数的namespace的描述

### ISSUE THREAD

**Issue by Zhengquan** [serverless-components/tencent-http#23]
链接：https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md#Faas

```yaml
  faas: # 函数配置相关
    framework: express
    runtime: Nodejs12.16
    name: webDemo # 云函数名称
    timeout: 10 # 超时时间，单位秒
    memorySize: 512 # 内存大小，单位MB
    environments: #  环境变量
      - key: envKey
        value: envValue
    vpc: # 私有网络配置
      vpcId: 'vpc-xxx' # 私有网络的Id
      subnetId: 'subnet-xxx' # 子网ID
    layers:
      - name: layerName #  layer名称
        version: 1 #  版本
    tags:
      - key: tagKey
        value: tagValue
```
实际可以支持：

<img width="693" alt="image" src="https://user-images.githubusercontent.com/251222/169026339-475e8a48-36a8-4b74-a135-5f9c3fbc71a7.png">
